In [2]:
import warnings

import pandas as pd
import psycopg2

warnings.filterwarnings("ignore")

In [3]:
user_25='app_pyc_lectura'
password_25="qtyKVT#2"
host_25="172.27.10.14"
port_25=5432
dbname_25="DB_Reporting"

In [ ]:
con = psycopg2.connect(
user=user_25,
password=password_25,
host=host_25,
port=port_25,
dbname=dbname_25
)

sql_query = """
SELECT
* FROM public.vw_emt_gc_detalle_ivr
WHERE organizacion = 'emtelcosas'
  AND division IN (
      'Alkosto',
      'Home,Alkosto',
      'Alkosto,Home'
  )
  AND fecha_inicio >= '2026-06-01'
  AND fecha_inicio <= '2026-06-30'
ORDER BY fecha_inicio
;
"""
df = pd.read_sql_query(sql_query, con)

In [7]:
df

,organizacion,id_conversacion,ani,dnis,division,nombre_ivr,fecha_hora_ingreso,fecha_hora_fin,duracion_ivr,duracion_navegacion,...,traza_opciones,ultima_opcion,tipo_ult_opcion,paso_ce,tipo_desconexion,id_campana,atributos_custom,custom_50,fecha_inicio,fecha_fin
0,emtelcosas,cf4f70d2-94a8-44fd-b36b-00eeae004aed,+573106957492,+576014073033,Alkosto,"ALK_IVR_PRINCIPAL,ALK_IVR_ENCUESTA_SAC,Default...",2026-06-01 11:24:45.337,2026-06-01 11:33:51.087,73388,72560,...,|0;Inicio IVR ;0|17;Menu principal;18914|7;Gar...,902;Segunda pregunta SAC;15292,None,SI,External,None,{'custom2': '|2;Numero documento ingresado;796...,None,2026-06-01,2026-06-01

In [8]:
df = df.join(df["atributos_custom"].apply(pd.Series))

In [9]:
df

,organizacion,id_conversacion,ani,dnis,division,nombre_ivr,fecha_hora_ingreso,fecha_hora_fin,duracion_ivr,duracion_navegacion,...,custom_50,fecha_inicio,fecha_fin,custom2,custom11,custom16,custom22,custom28,custom29,custom30
0,emtelcosas,cf4f70d2-94a8-44fd-b36b-00eeae004aed,+573106957492,+576014073033,Alkosto,"ALK_IVR_PRINCIPAL,ALK_IVR_ENCUESTA_SAC,Default...",2026-06-01 11:24:45.337,2026-06-01 11:33:51.087,73388,72560,...,None,2026-06-01,2026-06-01,|2;Numero documento ingresado;79663756,|7;Existe habeas data;NO,|12;Usuario_Identificado_Con_ANI;NO,|100;Consulta ws ConsultaHabeasData;OK,|107;Consulta ws CheckAftersalesCases;OK,|108;Consulta ws GetClientByAni;NOK,